# Generated by Django 5.0 on 2024-05-20 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_menuitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='description',
        ),
    ]
