# Generated by Django 5.0 on 2024-05-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date_time',
        ),
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateField(default='2024-05-30'),
        ),
    ]
