# Generated by Django 5.0 on 2024-05-30 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_table_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='number_of_people',
        ),
    ]
