# Generated by Django 5.0 on 2024-07-09 16:49

import main.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_order_user_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='Photo',
            field=models.ImageField(null=True, upload_to=main.utils.user_directory_path),
        ),
    ]
